### ISSUE TITLE
下载的视频播放只停留在封面

### ISSUE THREAD

**Issue by StephanoGeorge** [SigureMo/mooc-dl#17]
- [x] 我确认这是一个 issue 而不是一个 problem

## 课程地址：

https://www.icourse163.org/course/HPU-1449724166?tid=1450160452

## 问题描述：

下载的视频播放只停留在封面 (VLC 3.0.11.1)

似乎不是有效的 mp4
```sh
$ file 5.1.1-中断的基本概念.mp4
5.1.1-中断的基本概念.mp4: data
```

ArchLinux
Python 3.8.5

## 报错信息：

无

**Comment by SigureMo** [comment]
同 VLC，遇到同样的问题了……貌似是 [VLC 对 ts 的支持问题](https://bbs.archlinux.org/viewtopic.php?id=159151)，名字改一下就可以播放，再改回去就不行

我稍后加一个使用 FFmpeg 合并的选项吧，反正用 VLC 大多都安装了 FFmpeg，~~只不过用 FFmpeg 会慢上好多好多~~（使用合适的参数貌似挺快的）

**Comment by SigureMo** [comment]
已完成于 001da8e0340e3a0bc1f8ada89484b77f032d59ab，手动修改 `config.json` 里的 `use_ffmpeg` 为 `true` 即可启用
