### ISSUE TITLE
🐛 使用其他路径保存不会下载视频

### ISSUE THREAD

**Issue by StephanoGeorge** [SigureMo/mooc-dl#18]
## 调用方式

```shell
$ python3 mooc-dl.py https://www.icourse163.org/course/PAEU-1003647009\?tid\=1450354443
```

## 环境信息

-  OS： ArchLinux
-  Python： 3.8.6
-  Others： 其它信息

## 问题简述

使用其他路径, 下载的文件夹里没有视频

https://www.icourse163.org/course/PAEU-1003647009?tid=1450354443

## 额外信息

在配置文件里使用过 `/tmp/...`, `/run/media/...` 位置, 但都没有视频. 使用默认配置会正常.

**Comment by SigureMo** [comment]
emmm 其他路径呢，比如 `/home/username/mooc-dl/`

**Comment by StephanoGeorge** [comment]
对不起, 发现原因是启用了 ffmpeg, 而非路径
