### ISSUE TITLE
✨ 字幕接口也许可以向 @xixixixixiao 交流一下

### ISSUE THREAD

**Issue by b4imetu** [SigureMo/mooc-dl#25]
## 特性描述

- 字幕接口也许可以向 @xixixixixiao 交流一下
- [xixixixixiao/mooc-downloader](https://github.com/xixixixixiao/mooc-downloader)
- 然后或许可以配合FFmpeg可以实现`内嵌字幕`的功能 并在config中增加一个选项

**Comment by SigureMo** [comment]
所以是下不了字幕还是怎么了，能把问题说清楚吗？？？

**Comment by b4imetu** [comment]
啊，README和config里面没有看到下载字幕的选项

```
下载文件类型，可选 1,3,4，分别代表视频、PDF、附件，默认全部下载
```

实际下载的话也没有下载到字幕。而且我在issue里搜`字幕`的时候，也只有 Issue #3 里你提到过暂无字幕接口…

希望实现的功能是自动下载字幕并`可选`是否将字幕内嵌merge到视频里面~

**Comment by b4imetu** [comment]
另外能麻烦删一下 Issue #24 吗，当时提的问题比较傻，我这也没有删除权限

**Comment by SigureMo** [comment]
那把下不到字幕的视频链接发给我啊，说了半天都没说到问题关键……

**Comment by SigureMo** [comment]
既然无事，那便如你所愿
