### ISSUE TITLE
🐛 PDF下载失败, 内容为XML

### ISSUE THREAD

**Issue by StephanoGeorge** [SigureMo/mooc-dl#27]
## 调用方式

```
py3 mooc-dl.py https://www.icourse163.org/course/CSU-1206894807
```

## 环境信息

-  OS： ArchLinux
-  Python： 3.9.5
-  Others： 校园网

## 问题简述

下载的PDF, 其中一些的内容为:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>error_expires_timeout</Message>
  <Resource>%2Fedu-lesson-pdfsrc%2F87738B322EFBC1702D16411A66CBB130-1574991673443</Resource>
  <RequestId>77b97717-bce8-4924-b8b3-8d73df430074</RequestId>
</Error>
```

## 预期行为

PDF可以正常阅读

## 额外信息

去网页上查看, 发现下载出错的PDF可以正常阅读

今天重新下载一遍, 发现有问题的PDF集合不是相同的

出错的PDF集合从列表中间开始, 一直到末尾

**Comment by SigureMo** [comment]
居然还能用的嘛(\*/ω＼\*)，我去看看是什么问题

**Comment by SigureMo** [comment]
emmm，没有找到问题……我下载的都正常……

> 出错的PDF集合从列表中间开始, 一直到末尾

也许是 PDF 链接有时效，由于一边下视频一边下 PDF 导致后面的 PDF 在下载时已经失效了，如果真是这样的话可以尝试重新下载 PDF，修改配置如下两行重新运行即可

``` json
{
  ...
  "overwrite": true,
  ...
  "file_types": [3],
  ...
}
```

**Comment by SigureMo** [comment]
> 也许是 PDF 链接有时效

喔喔果然是这样，在写上一个评论时候还有效的链接现在无效了，试试上面的解决方案，应该是可以的

**Comment by StephanoGeorge** [comment]
正常了, 谢谢
