### ISSUE TITLE
枯了，还是 variable 'ext' referenced before assignment

### ISSUE THREAD

**Issue by billchenchina** [SigureMo/mooc-dl#3]
https://github.com/Foair/course-crawler/issues/37#issuecomment-547760041
```shell
$ python mooc-dl.py  https://www.icourse163.org/course/0701TJU046-1003168003
线性代数学习指导 - 同济大学
1003168003
Traceback (most recent call last):
  File "mooc-dl.py", line 219, in <module>
    resource_list = get_resource(term_id, token)
  File "mooc-dl.py", line 160, in get_resource
    file_path += ext
UnboundLocalError: local variable 'ext' referenced before assignment
```

**Comment by billchenchina** [comment]
看来真的得从 m3u8 搞了。。前几天安卓中 M 让我从 1.26.0 更新到 1.27.0，而且不更新不让进 APP 的那种

**Comment by SigureMo** [comment]
唉……真是，怕啥来啥，没办法咯，我把 course-crawler 电脑端接口搬来，拼个 m3u8 吧，反正这个本来我就做了分段下载机制，现在倒省的我自己切了

不过不知道啥时候有空，你最近需要用嘛？

course-crawler 暂时没啥好的想法了，先不弄了，没时间

**Comment by billchenchina** [comment]
> 唉……真是，怕啥来啥，没办法咯，我把 course-crawler 电脑端接口搬来，拼个 m3u8 吧，反正这个本来我就做了分段下载机制，现在倒省的我自己切了
> 
> 不过不知道啥时候有空，你最近需要用嘛？
> 
> course-crawler 暂时没啥好的想法了，先不弄了，没时间

😂😂😂不着急啦~~有时间的时候完善一下就行w
毕竟开源项目，都是用爱发电~辛苦啦www

**Comment by SigureMo** [comment]
@billchenchina 

简单支持了下，你可以试下，尽可能一次下载完吧，因为断点恢复机制可能还没弄好，另外字幕我也没找接口，等有需求了再说，中 M 上需要字幕的课程也不多

还有就是因为片段实在太多太小了，所以在所有文件下载前获取完整大小需要大量时间（我都没获取完过，太费时间了），所以我就改成边下边获取了，但是这样的话进度条体验极差……刚获取完大小就下完了，进度条一直是满的……

有问题再说吧，应该是能用的，只不过体验可能不太好
