### ISSUE TITLE
调用时出现相关json解析出错

### ISSUE THREAD

**Issue by TanLinRu** [SigureMo/mooc-dl#30]
## 调用方式

python mooc-dl.py https://www.icourse163.org/course/ZJU-93001?tid=1003997005

## 环境信息
-  OS： win10 
-  Python： Python 3.7

## 问题简述

在调用相关命令时，出现
```
数据结构 - 浙江大学
93001
Traceback (most recent call last):
  File "E:\project\mooc-dl\mooc-dl.py", line 227, in <module>
    resource_list = get_resource(term_id, token, file_types=CONFIG["file_types"])
  File "E:\project\mooc-dl\mooc-dl.py", line 139, in get_resource
    course_info = get_courseinfo(term_id, token)
  File "E:\project\mooc-dl\mooc-dl.py", line 56, in get_courseinfo
    print('res响应结果：{},data:{}'.format(res.josn(),data))
AttributeError: 'Response' object has no attribute 'josn'
```
无法解析相关的一个返回结果

**Comment by SigureMo** [comment]
？你确定这报错不是你自己改完代码后出现的？

**Comment by TanLinRu** [comment]
没有的，没改动代码前我运行，也是一样的错误。后续只是增加了相关的的打印



---原始邮件---
发件人: "Nyakku ***@***.***&gt;
发送时间: 2021年9月2日(周四) 中午12:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SigureMo/mooc-dl] 调用时出现相关json解析出错 (#30)




 
？你确定这报错不是改完代码后出现的？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SigureMo** [comment]
重新定义「一样的错误」

```
Traceback (most recent call last):
  File "./mooc-dl/mooc-dl.py", line 226, in <module>
    resource_list = get_resource(term_id, token, file_types=CONFIG["file_types"])
  File "./mooc-dl/mooc-dl.py", line 139, in get_resource
    for chapter_num, chapter in enumerate(course_info.get("results").get("termDto").get("chapters")):
AttributeError: 'NoneType' object has no attribute 'get'
```

你所描述的错误是由于自己加 print 时拼写错误导致的，这对错误定位没有丝毫帮助。

问题已解决，见 7383f448448ab8831d4cda1e5f5658e65bd2a41a
