### ISSUE TITLE
部分课程无法下载

### ISSUE THREAD

**Issue by extremk** [SigureMo/mooc-dl#4]
https://www.icourse163.org/course/0-1002607039?tid=1205951206
医学物理学 山东大学 无法下载，下载卡住

有机化学（上） - 大连理工大学
https://www.icourse163.org/course/0-44001?tid=1206054209
课件无法下载，导致卡住

**Comment by SigureMo** [comment]
修复了下 你试试

另外，弱弱问一句，其他课程下载正常吗，我没进行完整的测试

**Comment by extremk** [comment]
我还在大面积测试中，我1天最多能下200门课程，随时给你反馈，麻烦作者了

**Comment by SigureMo** [comment]
呃 太夸张了吧……你这是要干嘛？商业目的我是拒绝的，这点请你理解，我在 README.md 中也说明了这一点

**Comment by extremk** [comment]
没有商业目的，只是有点收集癖而已

**Comment by extremk** [comment]
好多年以前下载了不少有用的资料，当时不知道能用来干什么，很多年以后想要用时却找不到了

**Comment by SigureMo** [comment]
不过不得不说，你的硬盘真大，200门我可下不起……

**Comment by extremk** [comment]
我测试表明一门平均5G多一点，200也就1T，谈不上特别大，总感觉留了硬盘空间不存点东西是浪费。
大学的时候下载了经济师，建造师课程，后面删了，现在想用了，结果找不到，早早删了。
VeryCD也不提供下载了，可惜，所以现在看到好点的资料就想下载，怕网站关了。
