### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by XuYj1020** [SigureMo/mooc-dl#44]
## 调用方式

python mooc-dl.py "https://www.icourse163.org/learn/kaopei-1463848162?tid=1464722441#/learn/announce"

## 环境信息

-  OS： win10
-  Python： 3.10.9

## 问题简述

1.  发生的问题
    - 该程序是否不支持下载已购课程

2. 报错信息 
    - 无法获取课程信息！

3.  课程地址
    - https://www.icourse163.org/learn/kaopei-1463848162?tid=1464722441#/learn/announce

## 额外信息

- 使用账号已购买对应课程
- 公开课可以正常下载

**Comment by SigureMo** [comment]
> 该程序是否不支持下载已购课程

没试过，如果不能下就不支持，本项目几年前就进入维护阶段，因此也不会支持
