### ISSUE TITLE
🐛 無法下載 出現 TypeError: 'NoneType' 

### ISSUE THREAD

**Issue by greedtea** [SigureMo/mooc-dl#45]
## 调用方式

python mooc-dl.py "https://www.icourse163.org/course/NJUE-1458311167" 

## 环境信息

-  OS： windows 10
-  Python： Python 3.10.9

## 问题简述

Python大数据分析 - 南京财经大学
1458311167
Traceback (most recent call last):
  File "Z:\mooc-dl-master\mooc-dl.py", line 318, in <module>
    url, file_path, params = parse_resource(resource, token)
  File "Z:\mooc-dl-master\mooc-dl.py", line 199, in parse_resource
    pdf_url = res.json()["results"]["learnInfo"]["textOrigUrl"]
TypeError: 'NoneType' object is not subscriptable

**Comment by expoli** [comment]
这个问题，我也遇到了，是在解析 pdf 文件路径的时候出现的问题，可以暂时在 config 里面把 pdf 下载关闭

**Comment by greedtea** [comment]
想修改程式,不過案F12 檢查,會出現debugger ,不給看下載內容, 有方法可以破解?
