### ISSUE TITLE
🐛 课程权限已到期

### ISSUE THREAD

**Issue by fztransit** [SigureMo/mooc-dl#47]
## 调用方式

python mooc-dl.py https://www.icourse163.org/course/BUCT-1002990004?tid=1470662444

## 环境信息

-  OS： Windows 10
-  Python： Python 3.9.6

## 问题简述

控制台报错：[ERROR] 无法获取课件信息！原因：「课程权限已到期，请重新购买」，疑似该课程已关闭。
调试程序后发现在mooc-dl.py文件中的get_courseinfo()函数返回值为：{'status': {'code': 403, 'message': '课程权限已到期，请重新购买'}, 'results': None, 'extraInfo': None}。

测试了多个课程链接，都有这样的报错。

**Comment by SigureMo** [comment]
现在看来必须要参加课程才行了，所以请使用自己的账号参加课程再下载
