### ISSUE TITLE
icourse163 下载不了了

### ISSUE THREAD

**Issue by 121786404** [SigureMo/mooc-dl#8]
## （请在这里填写错误简述）
python3 mooc-dl.py https://www.icourse163.org/learn/FUDAN-1456632162?tid=1457131443
下载不了了，
大佬，能否修一下啊。

- [ ] 我确认这是一个 issue 而不是一个 problem

课程地址：（请在这里填写课程地址）

问题描述：（请在这里填写问题描述）

报错信息：（请在这里粘贴你的报错信息）

**Comment by SigureMo** [comment]
为什么不按照模板写？

**Comment by SigureMo** [comment]
把模板完善，我这里运行正常

**Comment by SigureMo** [comment]
长时间无回应，暂时关闭本 issue，如果有问题可以 reopen
